### ISSUE TITLE
Sounds won't play on Ipad and Android

### ISSUE THREAD

**Issue by mnmllink** [natemago/tabata-timer#2] opened 2015-01-20 08:40 UTC
Sounds won't play on any mobil devices! Please help me to fix that :) Thanks

**Comment by natemago** [comment] 2015-01-20 19:57
Will look into it :)

**Comment by ntld** [comment] 2015-01-25 20:00
any progress so far? :)

**Comment by natemago** [comment] 2015-05-21 20:18
The problem is that the sound won't play (although no error is reported by the audio element itself) if the sound is created and loaded programatically from JavaScript without user interaction. But, it will play if the load is triggered by some sort of user event (on click for example).

Tested this on andoird 4.4 and seems to be the solution for the problem. 

Will fix it shortly.

**Comment by natemago** [comment] 2015-05-21 20:40
Fixed the issue and tested it on Android 4.4.
The fix is also available on the [Tabata Timer Site](http://natemago.github.io/tabata-timer/) and you should be able to hear sounds.

Plese check it and verify if it works.

**Comment by ntld** [comment] 2015-05-21 20:43
Hey,

thanks for fixing this… working fine on Ipad and Android now!!

Cheers 

> Am 21.05.2015 um 22:40 schrieb Pavle Jonoski <notifications@github.com>:
> 
> Tabata Timer Site <http://natemago.github.io/tabata-timer/>

**Comment by natemago** [comment] 2015-05-21 20:51
Thanks for the quick feedback. I'm closing the ticket.

**Closed as completed by natemago** 2015-05-21 20:51 UTC
Labels: bug
